/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated from airoha-pon-daemons omci/schema.rs — do not edit by hand. */
#include "omci_schema.h"
#include <string.h>

static const struct me_attr onu_data_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr cardholder_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 20,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 20,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr circuit_pack_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 8,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 14,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 20,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 12, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 13, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 14, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr software_image_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 14,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr ethernet_uni_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 13, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 14, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 15, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr mac_bridge_service_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 1, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 2, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 3, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 5, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 7, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 9, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 11, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 12, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 13, .upload = true,
	},
};

static const struct me_attr mac_bridge_port_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 2, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 3, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 4, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 6, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 8, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 10, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 11, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 12, .upload = true,
	},
	{ .index = 10, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 6,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0xff, 0xff},
		.def_len = 2,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0xff, 0xff},
		.def_len = 2,
	},
	{ .index = 13, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 13, .upload = true,
	},
};

static const struct me_attr filter_preassign_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr vlan_filter_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 24,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 24, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 25, .upload = true,
	},
};

static const struct me_attr ieee_8021p_mapper_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 2, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 4, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 6, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 8, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 10, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 12, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 14, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 16, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 18, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 24,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 19, .upload = true,
	},
	{ .index = 13, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_OPTIONAL, .create_offset = 20, .upload = true,
	},
};

static const struct me_attr olt_g_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 20,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 14,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 14,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr power_shedding_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 12, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr extended_vlan_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0, 32},
		.def_len = 2,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0x81, 0x00},
		.def_len = 2,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0x81, 0x00},
		.def_len = 2,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_TABLE, .length = 16,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 1, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 24,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr onu_g_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 14,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 8,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 24,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 12,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 13, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr onu2_g_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 20,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 13, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 14, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr tcont_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0xff, 0xff},
		.def_len = 2,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){1},
		.def_len = 1,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr ani_g_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 13, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 14, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 15, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 16, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr uni_g_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr gem_interworking_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 2, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 3, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 5, .upload = true,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 7, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr gem_port_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 2, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 4, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 5, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 7, .upload = true,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 9, .upload = true,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 11, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr gal_profile_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr priority_queue_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0xff, 0xff},
		.def_len = 2,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0, 4},
		.def_len = 2,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){1},
		.def_len = 1,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0xff, 0xff},
		.def_len = 2,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr traffic_scheduler_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){1},
		.def_len = 1,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr traffic_descriptor_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 4, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 8, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 12, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 16, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 17, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 18, .upload = true,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 19, .upload = true,
	},
};

static const struct me_attr multicast_gem_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 2, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 3, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 5, .upload = true,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 7, .upload = true,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 9, .upload = true,
	},
	{ .index = 9, .access = ATTR_RW, .kind = ATTR_TABLE, .length = 12,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr omci_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_TABLE, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_TABLE, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr multicast_operations_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 1, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 2, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 3, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 5, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 6, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_TABLE, .length = 24,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_TABLE, .length = 24,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_TABLE, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 10, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 10, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 11, .upload = true,
	},
	{ .index = 12, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 15, .upload = true,
	},
	{ .index = 13, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 19, .upload = true,
	},
	{ .index = 14, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 15, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 16, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 3,
	  .create = CREATE_REQUIRED, .create_offset = 23, .upload = true,
	},
};

static const struct me_attr multicast_subscriber_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 1, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 3, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 5, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 9, .upload = true,
	},
};

static const struct me_attr multicast_monitor_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_TABLE, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_TABLE, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr veip_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 25,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0xff, 0xff},
		.def_len = 2,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr enhanced_security_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 16,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_TABLE, .length = 17,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){1},
		.def_len = 1,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_TABLE, .length = 16,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_TABLE, .length = 16,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_TABLE, .length = 17,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 8, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 10, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 16,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 11, .access = ATTR_RW, .kind = ATTR_TABLE, .length = 18,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 12, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
		.def = (const uint8_t[]){0, 128},
		.def_len = 2,
	},
};

static const struct me_attr ctc_loid_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 24,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 12,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
};

static const struct me_attr threshold_attributes[] = {
	{ .index = 1, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 4, .upload = true,
	},
	{ .index = 3, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 8, .upload = true,
	},
	{ .index = 4, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 12, .upload = true,
	},
	{ .index = 5, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 16, .upload = true,
	},
	{ .index = 6, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 20, .upload = true,
	},
	{ .index = 7, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_REQUIRED, .create_offset = 24, .upload = true,
	},
};

static const struct me_attr ethernet_pm_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 10, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 11, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 12, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 13, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 14, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 15, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 16, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr ethernet_pm_2_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr gem_port_pm_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 8,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 8,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 8,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 8,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr fec_pm_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr mac_bridge_port_pm_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr ethernet_frame_extended_pm_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 16,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
	{ .index = 3, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 4, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 5, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 6, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 7, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 8, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 9, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 10, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 11, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 12, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 13, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 14, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 15, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
	{ .index = 16, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 4,
	  .create = CREATE_NONE, .create_offset = 0, .upload = false,
	},
};

static const struct me_attr vendor_351_attributes[] = {
	{ .index = 1, .access = ATTR_RO, .kind = ATTR_SCALAR, .length = 1,
	  .create = CREATE_NONE, .create_offset = 0, .upload = true,
	},
	{ .index = 2, .access = ATTR_RW, .kind = ATTR_SCALAR, .length = 2,
	  .create = CREATE_REQUIRED, .create_offset = 0, .upload = true,
	},
};

const struct me_def pond_me_table[] = {
	{ .class_id = CLASS_ONU_DATA, .name = "ONU data", .origin = ME_ORIGIN_ONU,
	  .actions = 0x0000fb00u, .attrs = onu_data_attributes, .n_attrs = sizeof(onu_data_attributes) / sizeof(onu_data_attributes[0]) },
	{ .class_id = CLASS_CARDHOLDER, .name = "Cardholder", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = cardholder_attributes, .n_attrs = sizeof(cardholder_attributes) / sizeof(cardholder_attributes[0]) },
	{ .class_id = CLASS_CIRCUIT_PACK, .name = "Circuit pack", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = circuit_pack_attributes, .n_attrs = sizeof(circuit_pack_attributes) / sizeof(circuit_pack_attributes[0]) },
	{ .class_id = CLASS_SOFTWARE_IMAGE, .name = "Software image", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000200u, .attrs = software_image_attributes, .n_attrs = sizeof(software_image_attributes) / sizeof(software_image_attributes[0]) },
	{ .class_id = CLASS_PPTP_ETHERNET_UNI, .name = "PPTP Ethernet UNI", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = ethernet_uni_attributes, .n_attrs = sizeof(ethernet_uni_attributes) / sizeof(ethernet_uni_attributes[0]) },
	{ .class_id = CLASS_ETHERNET_PM_HISTORY_DATA, .name = "Ethernet PM history data", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = ethernet_pm_attributes, .n_attrs = sizeof(ethernet_pm_attributes) / sizeof(ethernet_pm_attributes[0]) },
	{ .class_id = CLASS_MAC_BRIDGE_SERVICE_PROFILE, .name = "MAC bridge service profile", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = mac_bridge_service_attributes, .n_attrs = sizeof(mac_bridge_service_attributes) / sizeof(mac_bridge_service_attributes[0]) },
	{ .class_id = CLASS_MAC_BRIDGE_PORT_CONFIG_DATA, .name = "MAC bridge port configuration data", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = mac_bridge_port_attributes, .n_attrs = sizeof(mac_bridge_port_attributes) / sizeof(mac_bridge_port_attributes[0]) },
	{ .class_id = CLASS_MAC_BRIDGE_PORT_PM_HISTORY_DATA, .name = "MAC bridge port PM history data", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = mac_bridge_port_pm_attributes, .n_attrs = sizeof(mac_bridge_port_pm_attributes) / sizeof(mac_bridge_port_pm_attributes[0]) },
	{ .class_id = CLASS_MAC_BRIDGE_PORT_FILTER_PREASSIGN_DATA, .name = "MAC bridge port filter preassign table", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = filter_preassign_attributes, .n_attrs = sizeof(filter_preassign_attributes) / sizeof(filter_preassign_attributes[0]) },
	{ .class_id = CLASS_VLAN_TAGGING_FILTER, .name = "VLAN tagging filter data", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = vlan_filter_attributes, .n_attrs = sizeof(vlan_filter_attributes) / sizeof(vlan_filter_attributes[0]) },
	{ .class_id = CLASS_ETHERNET_PM_HISTORY_DATA_2, .name = "Ethernet PM history data 2", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = ethernet_pm_2_attributes, .n_attrs = sizeof(ethernet_pm_2_attributes) / sizeof(ethernet_pm_2_attributes[0]) },
	{ .class_id = CLASS_IEEE_8021P_MAPPER, .name = "IEEE 802.1p mapper service profile", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = ieee_8021p_mapper_attributes, .n_attrs = sizeof(ieee_8021p_mapper_attributes) / sizeof(ieee_8021p_mapper_attributes[0]) },
	{ .class_id = CLASS_OLT_G, .name = "OLT-G", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = olt_g_attributes, .n_attrs = sizeof(olt_g_attributes) / sizeof(olt_g_attributes[0]) },
	{ .class_id = CLASS_ONU_POWER_SHEDDING, .name = "ONU power shedding", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = power_shedding_attributes, .n_attrs = sizeof(power_shedding_attributes) / sizeof(power_shedding_attributes[0]) },
	{ .class_id = CLASS_EXTENDED_VLAN_TAGGING, .name = "Extended VLAN tagging operation configuration data", .origin = ME_ORIGIN_OLT,
	  .actions = 0x24000350u, .attrs = extended_vlan_attributes, .n_attrs = sizeof(extended_vlan_attributes) / sizeof(extended_vlan_attributes[0]) },
	{ .class_id = CLASS_VENDOR_247, .name = "Vendor class 247", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000200u, .attrs = NULL, .n_attrs = 0 },
	{ .class_id = CLASS_ONU_G, .name = "ONU-G", .origin = ME_ORIGIN_ONU,
	  .actions = 0x01000300u, .attrs = onu_g_attributes, .n_attrs = sizeof(onu_g_attributes) / sizeof(onu_g_attributes[0]) },
	{ .class_id = CLASS_ONU2_G, .name = "ONU2-G", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = onu2_g_attributes, .n_attrs = sizeof(onu2_g_attributes) / sizeof(onu2_g_attributes[0]) },
	{ .class_id = CLASS_TCONT, .name = "T-CONT", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = tcont_attributes, .n_attrs = sizeof(tcont_attributes) / sizeof(tcont_attributes[0]) },
	{ .class_id = CLASS_ANI_G, .name = "ANI-G", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = ani_g_attributes, .n_attrs = sizeof(ani_g_attributes) / sizeof(ani_g_attributes[0]) },
	{ .class_id = CLASS_UNI_G, .name = "UNI-G", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = uni_g_attributes, .n_attrs = sizeof(uni_g_attributes) / sizeof(uni_g_attributes[0]) },
	{ .class_id = CLASS_GEM_INTERWORKING_TP, .name = "GEM interworking termination point", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = gem_interworking_attributes, .n_attrs = sizeof(gem_interworking_attributes) / sizeof(gem_interworking_attributes[0]) },
	{ .class_id = CLASS_GEM_PORT_PM_HISTORY_DATA, .name = "GEM port PM history data", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = gem_port_pm_attributes, .n_attrs = sizeof(gem_port_pm_attributes) / sizeof(gem_port_pm_attributes[0]) },
	{ .class_id = CLASS_GEM_PORT_NETWORK_CTP, .name = "GEM port network CTP", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = gem_port_attributes, .n_attrs = sizeof(gem_port_attributes) / sizeof(gem_port_attributes[0]) },
	{ .class_id = CLASS_GAL_ETHERNET_PROFILE, .name = "GAL Ethernet profile", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = gal_profile_attributes, .n_attrs = sizeof(gal_profile_attributes) / sizeof(gal_profile_attributes[0]) },
	{ .class_id = CLASS_THRESHOLD_DATA_1, .name = "Threshold data 1", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = threshold_attributes, .n_attrs = sizeof(threshold_attributes) / sizeof(threshold_attributes[0]) },
	{ .class_id = CLASS_THRESHOLD_DATA_2, .name = "Threshold data 2", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = threshold_attributes, .n_attrs = sizeof(threshold_attributes) / sizeof(threshold_attributes[0]) },
	{ .class_id = CLASS_PRIORITY_QUEUE, .name = "Priority queue", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = priority_queue_attributes, .n_attrs = sizeof(priority_queue_attributes) / sizeof(priority_queue_attributes[0]) },
	{ .class_id = CLASS_TRAFFIC_SCHEDULER, .name = "Traffic scheduler", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = traffic_scheduler_attributes, .n_attrs = sizeof(traffic_scheduler_attributes) / sizeof(traffic_scheduler_attributes[0]) },
	{ .class_id = CLASS_TRAFFIC_DESCRIPTOR, .name = "GEM traffic descriptor", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = traffic_descriptor_attributes, .n_attrs = sizeof(traffic_descriptor_attributes) / sizeof(traffic_descriptor_attributes[0]) },
	{ .class_id = CLASS_MULTICAST_GEM_INTERWORKING_TP, .name = "Multicast GEM interworking termination point", .origin = ME_ORIGIN_OLT,
	  .actions = 0x24000350u, .attrs = multicast_gem_attributes, .n_attrs = sizeof(multicast_gem_attributes) / sizeof(multicast_gem_attributes[0]) },
	{ .class_id = CLASS_OMCI, .name = "OMCI", .origin = ME_ORIGIN_ONU,
	  .actions = 0x04000200u, .attrs = omci_attributes, .n_attrs = sizeof(omci_attributes) / sizeof(omci_attributes[0]) },
	{ .class_id = CLASS_ETHERNET_PM_HISTORY_DATA_3, .name = "Ethernet PM history data 3", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = ethernet_pm_attributes, .n_attrs = sizeof(ethernet_pm_attributes) / sizeof(ethernet_pm_attributes[0]) },
	{ .class_id = CLASS_MULTICAST_OPERATIONS_PROFILE, .name = "Multicast operations profile", .origin = ME_ORIGIN_OLT,
	  .actions = 0x24000350u, .attrs = multicast_operations_attributes, .n_attrs = sizeof(multicast_operations_attributes) / sizeof(multicast_operations_attributes[0]) },
	{ .class_id = CLASS_MULTICAST_SUBSCRIBER_CONFIG, .name = "Multicast subscriber configuration info", .origin = ME_ORIGIN_OLT,
	  .actions = 0x00000350u, .attrs = multicast_subscriber_attributes, .n_attrs = sizeof(multicast_subscriber_attributes) / sizeof(multicast_subscriber_attributes[0]) },
	{ .class_id = CLASS_MULTICAST_SUBSCRIBER_MONITOR, .name = "Multicast subscriber monitor", .origin = ME_ORIGIN_OLT,
	  .actions = 0x24000350u, .attrs = multicast_monitor_attributes, .n_attrs = sizeof(multicast_monitor_attributes) / sizeof(multicast_monitor_attributes[0]) },
	{ .class_id = CLASS_FEC_PM_HISTORY_DATA, .name = "FEC PM history data", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = fec_pm_attributes, .n_attrs = sizeof(fec_pm_attributes) / sizeof(fec_pm_attributes[0]) },
	{ .class_id = CLASS_VEIP, .name = "Virtual Ethernet interface point", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = veip_attributes, .n_attrs = sizeof(veip_attributes) / sizeof(veip_attributes[0]) },
	{ .class_id = CLASS_ENHANCED_SECURITY_CONTROL, .name = "Enhanced security control", .origin = ME_ORIGIN_ONU,
	  .actions = 0x04000300u, .attrs = enhanced_security_attributes, .n_attrs = sizeof(enhanced_security_attributes) / sizeof(enhanced_security_attributes[0]) },
	{ .class_id = CLASS_ETHERNET_FRAME_EXTENDED_PM, .name = "Ethernet frame extended PM", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = ethernet_frame_extended_pm_attributes, .n_attrs = sizeof(ethernet_frame_extended_pm_attributes) / sizeof(ethernet_frame_extended_pm_attributes[0]) },
	{ .class_id = CLASS_VENDOR_351, .name = "Vendor class 351", .origin = ME_ORIGIN_OLT,
	  .actions = 0x10000350u, .attrs = vendor_351_attributes, .n_attrs = sizeof(vendor_351_attributes) / sizeof(vendor_351_attributes[0]) },
	{ .class_id = CLASS_CTC_LOID_AUTH, .name = "CTC LOID authentication", .origin = ME_ORIGIN_ONU,
	  .actions = 0x00000300u, .attrs = ctc_loid_attributes, .n_attrs = sizeof(ctc_loid_attributes) / sizeof(ctc_loid_attributes[0]) },
};

const size_t pond_me_table_len = sizeof(pond_me_table) / sizeof(pond_me_table[0]);

const struct me_def *pond_me_lookup(uint16_t class_id)
{
	for (size_t i = 0; i < pond_me_table_len; i++)
		if (pond_me_table[i].class_id == class_id)
			return &pond_me_table[i];
	return NULL;
}
