/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _AIROHA_XPON_NETLINK_H_
#define _AIROHA_XPON_NETLINK_H_

#define AIROHA_XPON_GENL_NAME    "xpon"
#define AIROHA_XPON_GENL_VERSION 1

enum airoha_xpon_mode {
	AIROHA_XPON_MODE_GPON = 1,
	AIROHA_XPON_MODE_XGPON,
	AIROHA_XPON_MODE_XGSPON,
	AIROHA_XPON_MODE_EPON_1G,
	AIROHA_XPON_MODE_EPON_10G_1G,
	AIROHA_XPON_MODE_EPON_10G_10G,
};

enum airoha_xpon_genl_command {
	AIROHA_XPON_CMD_UNSPEC,
	AIROHA_XPON_CMD_GET_LINE,
	AIROHA_XPON_CMD_SET_LINE,
	AIROHA_XPON_CMD_GET_STATUS,
};

enum airoha_xpon_genl_attribute {
	AIROHA_XPON_ATTR_UNSPEC,
	AIROHA_XPON_ATTR_IFINDEX,
	AIROHA_XPON_ATTR_MODE,
	AIROHA_XPON_ATTR_ACTIVE_MODE,
	AIROHA_XPON_ATTR_LINE,
	AIROHA_XPON_ATTR_FRONTEND,
	AIROHA_XPON_ATTR_REGISTRATION,
	AIROHA_XPON_ATTR_DATAPATH,
	AIROHA_XPON_ATTR_COUNTERS,
	__AIROHA_XPON_ATTR_MAX,
};

#define AIROHA_XPON_ATTR_MAX (__AIROHA_XPON_ATTR_MAX - 1)

/* Attribute numbers and types are part of the userspace ABI. */
enum airoha_xpon_line_attr {
	XPON_LINE_UNSPEC,
	XPON_LINE_CONFIGURED_MODE,
	XPON_LINE_ACTIVE_MODE,
	XPON_LINE_MODE_PENDING,
	XPON_LINE_LIFECYCLE,
	XPON_LINE_LAST_START_ERROR,
	XPON_LINE_OPTICAL_SIGNAL,
	XPON_LINE_RX_ACTIVE,
	XPON_LINE_PHY_READY,
	XPON_LINE_XGTC_SYNC,
	XPON_LINE_PCS_SYNC,
	XPON_LINE_PCS_PROFILE_VALID,
	XPON_LINE_PCS_PROFILE,
};

enum airoha_xpon_frontend_attr {
	XPON_FRONTEND_UNSPEC,
	XPON_FRONTEND_ERROR,
	XPON_FRONTEND_CALIBRATION,
	XPON_FRONTEND_TX_GATE_ENABLED,
	XPON_FRONTEND_TEMPERATURE_8472,
	XPON_FRONTEND_VOLTAGE_8472,
	XPON_FRONTEND_TX_BIAS_8472,
	XPON_FRONTEND_TX_POWER_8472,
	XPON_FRONTEND_RX_POWER_8472,
};

enum airoha_xpon_registration_attr {
	XPON_REGISTRATION_UNSPEC,
	XPON_REGISTRATION_ONU_STATE,
	XPON_REGISTRATION_ONU_ID_VALID,
	XPON_REGISTRATION_ONU_ID,
	XPON_REGISTRATION_MPCP_STATE,
	XPON_REGISTRATION_LLID_VALID,
	XPON_REGISTRATION_LLID,
	XPON_REGISTRATION_UPSTREAM_TX_ARMED,
	XPON_REGISTRATION_SERIAL_CONFIGURED,
	XPON_REGISTRATION_REGISTRATION_ID_CONFIGURED,
};

enum airoha_xpon_datapath_attr {
	XPON_DATAPATH_UNSPEC,
	XPON_DATAPATH_DATA_PATH_CONFIGURED,
	XPON_DATAPATH_SERVICE_READY,
};

enum airoha_xpon_counters_attr {
	XPON_COUNTERS_UNSPEC,
	XPON_COUNTERS_RX_START_COUNT,
	XPON_COUNTERS_XGTC_RX,
	XPON_COUNTERS_UPSTREAM_BURSTS_TX,
	XPON_COUNTERS_PLOAMD_RX,
	XPON_COUNTERS_PLOAMU_TX,
	XPON_COUNTERS_XGEM_RX,
	XPON_COUNTERS_XGEM_TX,
	XPON_COUNTERS_DISCOVERY_GATES,
	XPON_COUNTERS_REGISTER_REQUESTS,
	XPON_COUNTERS_REGISTER_MESSAGES,
	XPON_COUNTERS_REGISTER_ACKS,
	XPON_COUNTERS_REGISTER_NACKS,
	XPON_COUNTERS_MPCP_TIMEOUTS,
	XPON_COUNTERS_MAC_ERRORS,
	XPON_COUNTERS_SYNC_LOSSES,
	XPON_COUNTERS_RECOVERIES,
	XPON_COUNTERS_FULL_REINITIALIZATIONS,
};

#endif
